apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nginx
    name: nginx
  spec:
    replicas: 1
    selector:
      app: nginx
      deploymentconfig: nginx
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/container.nginx.image.entrypoint: '["nginx","-g","daemon off;"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nginx
          deploymentconfig: nginx
      spec:
        containers:
        - image: 172.30.107.183:5000/test2/nginx:latest
          name: nginx
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nginx
        from:
          kind: ImageStreamTag
          name: nginx:latest
          namespace: test2
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nginx
    name: nginx
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: nginx
      deploymentconfig: nginx
  status:
    loadBalancer: {}
kind: List
metadata: {}
